// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhdebserrnzytiqcfgaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoZGVic2Vycm56eXRpcWNmZ2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzNzM3MTksImV4cCI6MjA1MTk0OTcxOX0.r4IKogv-s7mVKBcyEaUDEbUQvpeXx84x5Tu3PfzZwsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);